### ISSUE TITLE
Are all the transports listed in the Readme.md actually supported?

### ISSUE THREAD

**Issue by hellais** [OperatorFoundation/shapeshifter-transports#2]
The `Readme.md` of this repo says:

> The following transports are currently provided by the library:
> - meek
> - obfs4
> - obfs3
> - obfs2
> - scramblesuit

However I see that actually only `obfs2` is being included in https://github.com/OperatorFoundation/shapeshifter-transports/blob/master/transports/transports.go#L81. I also don't see any code for `obfs3` or `scramblesuit` in the repo itself. There is code for `obfs4` (which looks like obfs4proxy from @yawning), but it doesn't seem to be imported by `transports.go`. I also see some glue code for shadowsocks, but it's unclear if that is also supported.

Are these PTs supported?

It would also be useful perhaps to make it clear from the readme that this is work in progress and that some bits are not yet working.

I would perhaps be interested t help out with this, if it were more clear what is missing and what is the current state and direction of the project.

**Comment by blanu** [comment]
The README has been updated. The currently supported transports are obfs2, obfs4, and Shadowsocks.
