### ISSUE TITLE
shapeshifter-dispatcher build breaking due to changes to dial function

### ISSUE THREAD

**Issue by seanwlx** [OperatorFoundation/shapeshifter-transports#3]
This commit https://github.com/OperatorFoundation/shapeshifter-transports/commit/4e221a11e8a72f50f15edc55eccdfea1f6213927 broke the build of shapeshifter-dispatcher due to the code expecting the old method signature for Dial() (without the error return value).  Even if the code in shapeshifter-dispatcher were updated it's still broken due to the change not being applied to obfs2 and dust.

**Comment by CryptoSax** [comment]
This issue has been resolved!  Code is no longer broken.
