### ISSUE TITLE
could we have semantic versioning?

### ISSUE THREAD

**Issue by meskio** [OperatorFoundation/shapeshifter-transports#8]
Now and then there are changes in the API of the transports that are not backward compatible (like few days ago adding the Dialer). In LEAP we use the obfs4 transport directly with a [little library grapper](https://0xacab.org/leap/shapeshifter). So every time the the API changes our code stops compiling.

Will be great if this repo starts doing semantic versioning. Since golang 1.11 there are support for modules:
https://github.com/golang/go/wiki/Modules

That implies basically create a go.mod file in the repo (I can send a pull-req for it) and add a tag to the repo for each release and incrementing the mayor number each time there is an API incompatibility change. This will allow us to pin a mayor version and only increase it when we adapt the code to the API changes.

How do you feel about that? Can I help in the process?

**Comment by CryptoSax** [comment]
We are actually discussing using go modules currently and will probably try to get that started soon!  and help would be greatly welcomed and appreciated!
